<!doctype html>
<html lang="en">
    <?php include 'links.php';?>
<body>
    
    <!-- header area -->
    <section class="header header--2">
  
    <!-- start menu area -->
        <?php include 'nav.php';?>
    <!-- end menu area -->

    </section><!-- end: .header -->

      <!-- end: .header -->
      <section class="padding-top">
        <div class="header-section">
            <div class="container-fluid padding-zero">
                <div class="row margin-zero">
                    <img alt="Terms & Conditions" class="full-width dev-hd-img" src="assets/img/term.jpg">                    
                </div>
            </div>
        </div>
        <!-- End Header Section-->
        <!-- Developement Process -->
        <div class="dev-process" id="dev-process">
            <div class="container">
                <!-- Welcome content -->
                <div class="row margin-top-20 margin-bottom-30">
                    <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
                        <h1 class="sub-heading hidden-md hidden-lg hidden-sm align-center">Terms of use</h1>
                        <h1 class="sub-heading">1. Introduction</h1>
                        <p>This agreement binds you or the company you represent ("you," or "your") to the terms and conditions set forth herein in connection with your use of LearnEngg platform including mobile applications, services or other offerings on our site LearnEngg.com </p>
                        <p>By using any of the company products, or clicking on the "signup" button, you agree to become bound by the terms and conditions of this agreement. If you do not agree to all the terms and conditions of this agreement, click on the "cancel" button and do not use the company products. Company's acceptance is expressly conditioned upon your assent to all the terms and conditions of this agreement.</p>
                        <h1 class="sub-heading">2. Additional terms</h1>
                        <p>Any personal information submitted in connection with your use of the products or the site is subject to our <a href="privacy.html">privacy policy</a>, located at privacy policy, which is hereby incorporated by reference into these terms.</p>
                        <p>If you are an   instructor (as defined below), you are also subject to the instructor terms and conditions located at instructor terms (the "instructor terms", which are hereby incorporated by reference into these terms. If you are an instructor and there is a conflict between these terms and the instructor terms, the instructor terms will govern.</p>
                        <h1 class="sub-heading">3. General</h1>
                        <p>The products enable students ("students") to connect with independent contractor instructors (the "instructors") who provide live and recorded instruction, tutoring, and learning services in our proprietary online platform. Students and instructors are, collectively, "users." the products include, without limitation, facilitating and hosting courses and supporting materials, and taking feedback from users.</p>
                        <p>Company reserves the right to revise these terms in its sole discretion at any time by posting the changes on the site. Changes become effective thirty (30) days after posting. Your continued use of products after change become effective shall mean that you accept those changes. You should visit the site regularly to ensure you are aware of the latest version of the terms. Notwithstanding the preceding sentences of this section, no revisions to these terms will apply to any dispute between you and the company that arose prior to the date of such revision.</p>
                        <p>The company may modify the products or discontinue their availability at any time.</p>
                        <p>You are solely responsible for all service, telephony, data charges and/or other fees and costs associated with your access to and use of the products, as well as for obtaining and maintaining all telephone, computer hardware, and other equipment required for such access and use.</p>
                        <p>If you elect to access or use products that involve payment of a fee, then you agree to pay, and will be responsible for payment of, that fee and all taxes associated with such access or use. If you provide credit card information to pay for such fees then you hereby represent and warrant that you are authorized to supply such information and hereby authorize the company to charge your credit card on a regular basis to pay the fees as they are due.</p>
                        <p>If your payment method fails or your account is past due, then we may collect fees owed using other collection mechanisms. This may include charging other payment methods on file with us and/or retaining collection agencies and legal counsel. We may also block your access to any products pending resolution of any amounts due by you to company.</p>
                        <p>All of your use, access and other activities relating to the site and the products must be in compliance with all applicable laws and regulations, including, without limitations, laws relating to copyright and other intellectual property use, and to privacy and personal identity. In connection with your use of the products and site, you must not provide incorrect or knowingly false information; copy, distribute, modify, reverse engineer, deface, tarnish, mutilate, hack, or interfere with the products or operation of the site; frame or embed the site or products; impersonate another person or gain unauthorized access to another person's account; introduce any virus, worm, spyware or any other computer code, file or program that may or is intended to damage or hijack the operation of any hardware, software or telecommunications equipment, or any other aspect of the products or operation of the site; scrape, spider, use a robot or other automated means of any kind to access the products.</p>
                        <h1 class="sub-heading">4. General disclaimer</h1>
                        <p>The site is only a marketplace for instructors and students. We do not hire or employ instructors nor are we responsible or liable for any interactions involved between the instructors and their respective clients. We are not responsible for disputes, claims, losses, injuries, or damage of any kind that might arise out of or relate to conduct of instructors or students, including, but not limited to, any student's reliance upon any information provided by an instructor.</p>
                        <p>We do not control submitted content (as defined below) posted on the site and, as such, do not guarantee in any manner the reliability, validity, accuracy or truthfulness of such submitted content. You also understand that by using the products may expose you to submitted content that you consider offensive, indecent, or objectionable. The company has no responsibility to keep such content from you and no liability for your access or use of any submitted content, to the extent permissible under applicable law.</p>
                        <p>The site and products may give you access to links to third-party websites ("third party sites"), either directly or through courses or instructors. The company does not endorse any of these third party sites and does not control them in any manner. Accordingly, the company does not assume any liability associated with third party sites. You need to take appropriate steps to determine whether accessing a third party site is appropriate, and to protect your personal information and privacy on such third party site.</p>
                        <h1 class="sub-heading">5. Conduct</h1>
                        <p>You may only access the products for lawful purposes. You are solely responsible for the knowledge of and adherence to any and all laws, rules, and regulations pertaining to your use of the products. You agree not to use the products or the company content (as defined below) to recruit, solicit, or contact in any form instructors or potential users for employment or contracting for a business not affiliated with us without our advance written permission, which may be withheld in our sole discretion. You assume any and all risks from any meetings or contact between you and any instructors or other users of the products.</p>
                        <h1 class="sub-heading">6. Specific obligations of students using the site.</h1>
                        <p>If you are a user in search of, or engaging, instructors, you represent, warrant and covenant that:</p>
                        <p>You have read, understood, and agree to be bound by the pricing information (see the pricing section below) before using the site or registering for a course;</p>
                        <p>If you are under the age of 18, you have obtained parental or legal guardian consent before using the site, contacting an instructor, or registering for a course.</p>
                        <p>You will not upload, post or otherwise transmit any unsolicited or unauthorized advertising, promotional materials, junk mail, spam, chain letters, pyramid schemes or any other form of solicitation (commercial or otherwise) through the site or the products;</p>
                        <p>You will not post any inappropriate, offensive, racist, hateful, sexist, pornographic, false, misleading, infringing, defamatory or libelous content;</p>
                        <p>You will not reproduce, distribute, publicly display, publicly perform, communicate to the public, create derivative works from or otherwise use and exploit any company content, the products or courses or submitted content except as permitted by these terms or the relevant instructor as applicable;</p>
                        <p>You will not disclose any personal information to an instructor, and otherwise will assume responsibility for controlling how your personal information is disclosed or used, including, without limitation, taking appropriate steps to protect such information; and</p>
                        <p>You will not solicit personal information from any instructor or other user.</p>
                        <h1 class="sub-heading">7. Registration</h1>
                        <p>To use certain products, you will need to register and obtain an account, username and password. When you register, the information you provide to us during the registration process will help us in offering content, customer service, and network management. You are solely responsible for maintaining the confidentiality of your account, username, and password (collectively, your "account") and for all activities associated with or occurring under your account. You represent and warrant that your account information will be accurate at all times. You must notify us (a) immediately of any unauthorized use of your account and any other breach of security, and (b) ensure that you exit from your account at the end of each use of the products. To the extent permissible under applicable law, we cannot and will not be responsible for any loss or damage arising from your failure to comply with the foregoing requirements or as a result of use of your account, either with or without your knowledge, prior to your notifying us of unauthorized access to your account.</p>
                        <p>You may not transfer your account to any other person and you may not use anyone else's account at any time without the permission of the account holder. In cases where you have authorized or registered another individual, including a minor, to use your account, you are fully responsible for (i) the online conduct of such user; (ii) controlling the user's access to and use of the products; and (iii) the consequences of any misuse.</p>
                        <h1 class="sub-heading">9. Content, licenses & permissions.</h1>
                        <p>All software, technology, designs, materials, information, communications, text, graphics, links, electronic art, animations, illustrations, artwork, audio clips, video clips, photos, images, reviews, ideas, and other data or copyrightable materials or content, including the selection and arrangements thereof is "content." where the company provides content to you in connection with the products, including, without limitation, the software and the products and the site, it is "company content." content uploaded, transmitted or posted to the site or through the products by a user is "submitted content." content remains the proprietary property of the person or entity supplying it (or their affiliated and/or third party providers and suppliers) and is protected, without limitation, pursuant to Indian and foreign copyright and other intellectual property laws. You hereby represent and warrant that you have all licenses, rights, consents, and permissions necessary to grant the rights set forth in these terms to company with respect to your submitted content and that company shall not need to obtain any licenses, rights, consents, or permissions from, or make any payments to, any third party for any use or exploitation of your submitted content as authorized in these terms or have any liability to you or any other party as a result of any use or exploitation of your submitted content as authorized in these terms.</p>
                        <p>You hereby grant the company a non-exclusive right and license to reproduce, distribute, publicly perform, offer, market and otherwise use and exploit the submitted content on the site and through the products, and sublicense it to instructors and users for these purposes directly or through third parties. Notwithstanding the foregoing, you have the right to remove all or any portion of your submitted content from the site at any time. Removal of your submitted content will terminate the foregoing license and rights sixty (60) days after such removal as to new uses, provided, however, that any rights given to users prior to that time will continue in accordance with the terms granted to such users.</p>
                        <p>The company hereby grants you (as a user) a limited, non-exclusive, non-transferable license to access and use submitted content and company content, for which you have paid all required fees, solely for your personal, non-commercial, educational purposes through the site and the products, in accordance with these terms and any conditions or restrictions associated with particular courses or products. All other uses are expressly prohibited absent our express written consent. You may not reproduce, redistribute, transmit, assign, sell, broadcast, rent, share, lend, modify, adapt, edit, create derivative works of, license, or otherwise transfer or use any submitted content or company content unless we give you explicit permission to do so. Submitted content and company content is licensed, and not sold, to you. Instructors may not grant you license rights to submitted content you access or acquire through the services and any such direct license shall be null and void and a violation of these terms.</p>
                        <p>You agree that we may record all or any part of any courses (including voice chat communications) for quality control and delivering, marketing, promoting, demonstrating or operating the site and the products. You hereby grant the company permission to use your name, likeness, image or voice in connection with offering, delivering, marketing, promoting, demonstrating, and selling the site, products, courses, company content and submitted content and waive any and all rights of privacy, publicity, or any other rights of a similar nature in connection therewith, to the extent permissible under applicable law.</p>
                        <p>The company respects all copyright, privacy, defamation and other laws relating to content and information and will not tolerate violation of such laws. Notwithstanding the foregoing, the company does not screen the submitted content and all use of the submitted content by you is at your own risk and the company shall have no liability for such use. In particular, no review or posting or appearance of the submitted content on the site or through the products is intended to act as an endorsement or representation that any submitted content is free of violation of any copyright, privacy or other laws or will suit a particular purpose or be accurate or useful. If you believe that submitted content of yours violates any law or regulation or is inaccurate or poses any risk whatsoever to a third party it is your responsibility to take such steps you deem necessary to correct the situation. If you believe that submitted content of a third party or any company content violates any laws or regulations, including, without limitation, any copyright laws, you should report it to the company in accordance with the procedures that we maintain at <a href="copyright.html">copyright</a> .</p>
                        <p>All rights not expressly granted in these terms are retained by the content owners and these terms do not grant any implied licenses</p>
                        <h1 class="sub-heading">9. Pricing for paid courses</h1>
                        <p><b>Pricing</b></p>
                        <p>Except when a course is made available through the LearnEngg marketing programs, or a course is offered on company's iOS / android mobile applications, an instructor will be solely responsible for determining the base price to be charged for such course, in accordance with the instructor terms. In the case of courses offered on company's iOS / android applications, company will select the app store price tier (app store pricing matrix available here) that is closest to the fee set by the instructor. When the sale currency is different than the base currency, the company will determine the sale price according to the most recent Base Exchange rate and applicable cost adjustment factor.</p>
                        <p>If you are a student, you agree to pay the fees for courses that you take, and hereby authorize us to charge your credit card for these amounts. We will charge your credit card monthly for all amounts owed. If your credit card is declined, you agree to pay us the fees within thirty (30) days of notification from us, and pay (at our discretion) a late payment charge at 1.5% per month, or the maximum permitted by law, whichever is greater.</p>
                        <p><b>Taxes</b></p>
                        <p><em>Indian government</em></p>
                        <p>In the event that the sale or delivery of a course or any submitted content to any student in the Indian Territory is subject to any service tax, under applicable law, the Company will collect and remit the service tax to the competent tax authorities for sales of such courses or submitted content to students in the Indian Territory. The company may at its own discretion increase the sale price where it is of the view that service tax may be due and it will have a liability to account for such. You will indemnify and hold the company harmless against any and all claims by any tax authority for any underpayment of service tax, and any penalties and/or interest thereon.</p>
                        <p><em>All other countries</em></p>
                        <p>For sales of any of courses or submitted content in countries other than the Indian Territory, you are responsible for remitting the taxes to the appropriate taxing authority (which may be different to the tax authority in your own location). The company is unable to provide you with tax advice and you should consult your own tax advisor.</p>
                        <p><em>Foreign currency</em></p>
                        <p>Company's online platform will default the sale currency based on your geographic location. The currency of any transaction will match the sale currency displayed to you on the website. You cannot change your displayed currency.</p>
                        <p>Each foreign currency conversion is processed at a foreign currency conversion rate. This rate generally refers to the amount of one currency that must be paid to buy a certain amount of another currency at a given time. For example, if it costs us$125.00 to buy €100.00, the currency conversion rate of us dollars to euros would be 1.25, and the currency conversion rate from euros to us dollars would be 0.8. Currency conversion rates will vary from time to time.</p>
                        <p><b>Refunds</b></p>
                        <p>In some cases, LearnEngg offers students a thirty (30)-day, no-questions-asked money back guarantee on courses that are not purchased through LearnEngg's iOS or android applications. If you, as a student, are unhappy with such a course and request a refund within thirty (30) days of the date that you paid for access to that course, we will provide you with a full refund of the amount you paid. To request a refund, please contact us via support@LearnEngg.com. Please note that if we believe that you are abusing our refund policy in our sole discretion, we reserve the right to suspend or terminate your account and refuse or restrict any and all current or future use of the company products, without any liability to you. In addition, please note that notwithstanding anything to the contrary in these terms, LearnEngg does not provide refunds for courses purchased through our iOS or android applications. All sales of courses through LearnEngg's iOS or android applications are final.</p>
                        <p>You, as an instructor, acknowledge and agree that students have the right to receive a refund as set forth in this section. Neither instructors nor company shall receive any payments, fees or commissions for any transactions for which a refund has been granted. In the event that a student requests a refund for a course after the company  has sent an instructor payment for that course, the company  reserves the right to either (1) deduct the amount of such refund from the next payment to be sent to that instructor, or (2) require that instructor to refund any amounts refunded to students for instructor's course to the extent no additional payments are due from the company  to instructor or such payments due instructor are insufficient to cover the amounts refunded to students.</p>
                        <h1 class="sub-heading">10. Trademarks</h1>
                        <p>The trademarks, service marks, and logos (the "trademarks") used and displayed on the site, in the products or in any company content are our registered or unregistered trademarks or of our suppliers or third parties and are protected pursuant to Indian and foreign trademark laws. All rights are reserved and you may not alter or obscure the trademarks, or link to them without our prior approval.</p>
                        <h1 class="sub-heading">11. Warranty disclaimer</h1>
                        <p>The products, site, company content, submitted content, courses, and any other materials made available on or through the site or the products are provided "as is," without any warranties of any kind and, to the fullest extent permissible under applicable law, the company hereby disclaims all such warranties, express or implied, including, but not limited to, warranties of merchantability, fitness for a particular purpose, non-infringement, accuracy, freedom from errors, suitability of content, or availability.</p>
                        <h1 class="sub-heading">13. Miscellaneous</h1>
                        <p>You hereby indemnify, defend and hold harmless the company, and its affiliates, officers, directors, agents, partners, employees, licensors, representatives and third party providers from and against all reasonably foreseeable losses, expenses, damages, costs, claims and demands, including reasonable attorneys' fees and related costs and expenses, due to or arising out of your breach of any representation or warranty hereunder. We reserve the right, at our own expense, to assume the exclusive defense and control of any matter otherwise subject to indemnification by you under this section 13, and in such case, you agree to fully cooperate as reasonably required with such defense and in asserting any available defenses.</p>
                        <h1 class="sub-heading">14. Termination</h1>
                        <p>We may terminate your use of the products or site immediately without notice for any breach by you of these terms or any of our applicable policies, as posted on the site from time to time. We may discontinue offering any product, course, or content at any time (which will terminate your right to offer these courses if you are an instructor). You may terminate your use of the site or the products at any time, either by ceasing to access them, or by contacting us at <a href="mailto:support@LearnEngg.com">support@LearnEngg.com</a> (but if you are an instructor then students enrolled in your courses prior to termination shall continue to have access to them for the duration of the course). We have no obligation to retain any of your account or submitted content for any period of time beyond what may be required by applicable law. Upon termination, you must cease all use of the site, products and content. Any accrued rights to payment and sections 4, 5, 10-15 and all representations and warranties shall survive termination.</p>
                        <h1 class="sub-heading">15. Electronic notices</h1>
                        <p>By using the products or communicating with company, you agree that company may communicate with you electronically regarding security, privacy, and administrative issues relating to your use of the products or these terms. If company learns of a security system's breach, company may attempt to notify you electronically by posting a notice on the products or sending an email to you. You may have a legal right to receive this notice in writing. To receive free written notice of a security breach (or to withdraw your consent from receiving electronic notice), please write to company at <a href="mailto:support@LearnEngg.com">support@LearnEngg.com</a></p>
                        <h1 class="sub-heading">16. Miscellaneous</h1>
                        <p>Entire agreement. These terms and any policies applicable to you posted on the site constitute the entire agreement between the parties with respect to the subject matter hereof, and supersede all previous written or oral agreements between the parties with respect to such subject matter.</p>
                        <p>Severability. If any provision of these terms is found to be illegal, void or unenforceable, then that provision shall be deemed severable from these terms and shall not affect the validity and enforceability of any remaining provisions of these terms.</p>
                        <p>Waiver. A provision of these terms may be waived only by a written instrument executed by the party entitled to the benefit of such provision. The failure of company to exercise or enforce any right or provision of these terms will not constitute a waiver of such right or provision.</p>
                        <p>Notice. Any notice or other communication to be given hereunder will be in writing and given by facsimile, postpaid registered or certified mail return receipt requested, or electronic mail.</p>
                        <p>No agency. Nothing in these terms shall be construed as making either party the partner, joint venture, agent, legal representative, employer, contractor or employee of the other. Neither the company nor any other party to this agreement shall have, or hold itself out to any third party as having, any authority to make any statements, representations or commitments of any kind, or to take any action that shall be binding on the other except as provided for herein or authorized in writing by the party to be bound.</p>
                        <p>These terms and your use of the site and the products shall be governed by the substantive laws of India, without reference to its choice or conflicts of law principles</p>

                    </div>
                </div> <!-- /Welcome content -->
            </div>
        </div>
      </section>
    
    <footer id="footer_section" class="footer5 footer--bw">
        <?php include 'footer.php';?>
    </footer>
   </body>
</html>